import type { Project } from '../../domain/types'
import { fmt } from '../../lib/money'
import { fmtDate } from '../../lib/date'
import { landAcquisitionCost, allInProjectCost } from './projectCost'

const esc = (s: unknown) =>
  String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] as string)

/** Open a clean, printable one-page project brief in a new window (Print → Save as PDF /
 *  share). A shareable summary of the project's baseline details. */
export function printProjectBrief(project: Project): void {
  const rows: [string, string][] = [
    ['Status', project.status],
    ['Priority', project.priority],
    ['Template', project.templateType],
    ['Construction budget', fmt(project.constructionBudget)],
    ['Contingency', fmt(project.contingencyBudget)],
    ['Lot / land purchase price', project.purchasePrice ? fmt(project.purchasePrice) : '—'],
    ['Closing costs', project.closingCosts ? fmt(project.closingCosts) : '—'],
    ['Land & acquisition total', landAcquisitionCost(project) ? fmt(landAcquisitionCost(project)) : '—'],
    ['All-in project cost', allInProjectCost(project) ? fmt(allInProjectCost(project)) : '—'],
    ['Square footage', project.squareFootage ? `${project.squareFootage.toLocaleString()} sqft` : '—'],
    ['Stories', project.stories ? String(project.stories) : '—'],
    ['Footprint', project.footprint || '—'],
    ['Basement', project.basement || '—'],
    ['Lot dimensions', project.lotDimensions || '—'],
    ['Proposed build', project.proposedBuildDimensions || '—'],
    ['Start date', project.startDate ? fmtDate(project.startDate) : '—'],
    ['Target finish', project.targetFinishDate ? fmtDate(project.targetFinishDate) : '—'],
  ]
  const html = `<!doctype html><html><head><meta charset="utf-8" />
<title>${esc(project.name)} — Project Brief</title>
<style>
  body { font: 15px/1.5 -apple-system, system-ui, sans-serif; color: #1a1a1a; max-width: 720px; margin: 2rem auto; padding: 0 1.5rem; }
  h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
  .addr { color: #666; margin: 0 0 1.5rem; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: .5rem .25rem; border-bottom: 1px solid #eee; vertical-align: top; }
  td:first-child { color: #666; width: 45%; }
  td:last-child { text-align: right; font-weight: 600; }
  h2 { font-size: 1rem; margin: 1.5rem 0 .25rem; }
  p.scope { white-space: pre-wrap; color: #333; }
  .foot { margin-top: 2rem; color: #999; font-size: .8rem; }
  @media print { body { margin: 0; } }
</style></head><body>
  <h1>${esc(project.name) || 'Project'}</h1>
  <p class="addr">${esc(project.address)}</p>
  <table>${rows.map(([k, v]) => `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</table>
  ${project.scopeSummary ? `<h2>Scope</h2><p class="scope">${esc(project.scopeSummary)}</p>` : ''}
  ${project.warrantyNotes ? `<h2>Warranty notes</h2><p class="scope">${esc(project.warrantyNotes)}</p>` : ''}
  <p class="foot">Generated by HomeBuild Pro</p>
</body></html>`
  const w = window.open('', '_blank', 'noopener,width=820,height=1000')
  if (!w) return
  w.document.write(html)
  w.document.close()
  w.focus()
  setTimeout(() => w.print(), 250)
}
